### ISSUE TITLE
Broken class diagram in documentation

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#229]
The [composite structure class diagram ([CDB]) in the generated documentation](https://dsd-dbs.github.io/py-capellambse/code/capellambse.model.crosslayer.html#module-capellambse.model.crosslayer.cs) has an error. This needs to be fixed.

**Comment by Wuestengecko** [comment]
As it's hard to read (black text on black background - unrelated other issue), here's the stack trace:

```
Traceback (most recent call last):
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/model/diagram.py", line 337, in __render_fresh
    self._render = self._create_diagram(params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/model/diagram.py", line 432, in _create_diagram
    return aird.parse_diagram(self._model._loader, self._element, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/__init__.py", line 187, in parse_diagram
    elm = _element_from_xml(
          ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/__init__.py", line 219, in _element_from_xml
    return factory(ebd)
           ^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_semantic.py", line 97, in from_xml
    return drawtype(seb)
           ^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 591, in association_factory
    edge = generic_factory(seb)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 67, in generic_factory
    snaptarget(edge, -1, -2, targetport, not edge.hidden, routingstyle)
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 295, in snaptarget
    snap_oblique(points, i, next_i, target)
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/aird/_edge_factories.py", line 305, in snap_oblique
    points[i] = target.vector_snap(
                ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_diagram.py", line 262, in vector_snap
    return self.__vector_snap_oblique(source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_diagram.py", line 278, in __vector_snap_oblique
    return diagram.line_intersect(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/py-capellambse/py-capellambse/capellambse/diagram/_vector2d.py", line 378, in line_intersect
    raise ValueError("Lines are parallel")
ValueError: Lines are parallel
```
