### ISSUE TITLE
Git worktree cleanup fails on Windows

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#490]
While cleaning up the Git worktree, this error occurs:

```
tests/test_filehandler_git.py::test_gitfilehandler_can_read_remote_files_no_revision
  C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\_pytest\unraisableexception.py:85: PytestUnraisableExceptionWarning: Exception ignored in: <finalize object at 0x258aa768ac0; dead>
  
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\weakref.py", line 591, in __call__
      return info.func(*info.args, **(info.kwargs or {}))
    File "D:\a\py-capellambse\py-capellambse\capellambse\filehandler\git.py", line 561, in __cleanup_worktree
      subprocess.run(
    File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\subprocess.py", line 526, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['git', 'worktree', 'remove', '-f', 'C:\\Users\\runneradmin\\AppData\\Local\\capellambse\\capellambse\\Cache\\worktrees\\capellambse-7004-iu7xk4g9']' returned non-zero exit status 255.
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

Failing to clean up the worktree can lead to excessive disk usage.

Additionally, after fixing this, we should configure pytest to fail if any unraisable exception was detected during a test.

**Comment by zusorio** [comment]
I ran into this issue when using the model explorer on Windows. Every time a reload is triggered due to a changed file, the error prevents it from properly restarting.
